[package]
name = "fractl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.1.8"
colorgrad = "0.6.2"
image = "0.24.5"
openh264 = "0.4.0"
rayon = "1.7.0"
